version: '3'

services:
  # main container for the Hagiz API application
  hagiz_app:
    container_name: hagiz_api
    build: .
    ports:
      - '4000:4000'
    env_file:
      - ./.env
  # MongoDB service for data storage    
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  # only for development purposes, provides a web interface for MongoDB
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
     
volumes:
  mongo-db:
